### ISSUE TITLE
Friday bootstrap portfolio code review

### ISSUE THREAD

**Issue by norbiboy1** [norbiboy1/Bootstrap-Portfolio#1]
The GitHub Issue is open for revisit my code:
😃 Thank you!

**Comment by Obimbo07** [comment]
Hi @norbiboy1   👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready! There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tajulafreen** [comment]
Hi Mr @norbiboy1,
Good job so far! 👏. Your Code is Awesome! 💪

There are a few issues 🐛 that you still need to work 🔧 on but you are almost there! 🏃

Don't Worry 🙏
It's ok to have bugs in your code 🐛. Especially if that's your first project 1️⃣ in Bootstrap. 

I am going to guide you on how to fix them down below. 🤓
For the mobile version: 👍

Kindly add a class for the responsive website.
example: expand-lg

✅ Thank you for distributing your project.
You did a really good job 😄

**Comment by Pi1998** [comment]
Hi @norbiboy1  , 👍 

# APPROVED 💯 🥇 

Your project is amazing!  There is nothing else to say other than Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>


## Optional suggestions
- It will be best if you implement the design for the mobile version. 💯 

## Cheers and Happy coding!👏👏👏

**Comment by norbiboy1** [comment]
Thanks for the comments: @Obimbo07, @tajulafreen, @Pi1998 ! :feelsgood: 
I will implement the mobile version today.
Happy coding my friends! 👨‍💻 👩‍💻.
Wish you all the best for all of you!!! 😄 💯
